# rts/settings.yaml

ticker: 'RTS'
ticker_lc: 'rts'
ticker_close: 'RIM6'  # Фьючерс для закрытия позиции (trade)
ticker_open: 'RIM6'   # Фьючерс для открытия позиции (trade)
quantity_close: 2
quantity_open: 2

# Модель для предсказания sentiment (для выбора правил)
sentiment_model: 'gemma3:12b'

# Выбор новостей по провайдеру
provider: 'investing_prime_interfax'
#provider: 'investing'
#provider: 'prime_interfax'

time_start: '21:00:00'  # Время начала торговой сессии (для фильтрации новостей)
time_end: '20:59:59'  # Время окончания торговой сессии (для фильтрации новостей)
num_mds: 200  # Количество последних интервалов (дней) для сохранения в markdown файлы
num_dbs: 8  # Количество последних файлов БД новостей для обработки
start_date_download_minutes: '2025-06-24'  # Дата начала загрузки минутных свечей

#md_path: 'C:/Users/Alkor/gd/md_rss_all'
md_path: 'C:/Users/Alkor/gd/md_rss_all_oil_gaz'

predict_path: 'C:/Users/Alkor/gd/predict_ai/{ticker_lc}_sentiment_gemma'
path_db_minute: 'C:/Users/Alkor/gd/data_quote_db/{ticker}_futures_minute_2025.db'
path_db_day: 'C:/Users/Alkor/gd/data_quote_db/{ticker}_futures_day_2025_21-00.db'
db_news_dir: 'C:/Users/Alkor/gd/db_rss'  # Директория с БД новостей (sqlite файлы)
sentiment_output_pkl: 'sentiment_scores.pkl'  # Файл для сохранения предсказанных sentiment (pickle)

# Окно дат для sentiment_group_stats.py
stats_date_from: '2025-09-01'
stats_date_to: '2027-01-01'

# Окно дат для sentiment_backtest.py
backtest_date_from: '2025-09-01'
backtest_date_to: '2027-01-01'
